### ISSUE TITLE
update readme for better reach

### ISSUE THREAD

**Issue by il3ven** [rugpullindex/svg-line-chart#43]
Based on the points listed at https://skerritt.blog/make-popular-open-source-projects/ I propose the following changes.

#### Deliverables
- Add a header that includes the following
  - Logo
  - One line slogan
- Quick Install / Usage
The current usage doesn't work.
- Create a separate file for API documentation. Link this into the Readme.
- Create a separate file for changelog
- Update screenshot

Do we need to add anything else?

#### Time Estimate
4 hours

**Comment by TimDaub** [comment]
> Do we need to add anything else?

Looks like a nice list to get started on. 👍🏼
