### ISSUE TITLE
define `.prettierrc` in the repo

### ISSUE THREAD

**Issue by il3ven** [rugpullindex/svg-line-chart#44]
Prettier is a useful tool which increases code readability. Since many people are working on the repo it is important that everyone uses the same formatting configuration.

An example where a formatting problem arose: https://github.com/rugpullindex/svg-line-chart/pull/34#discussion_r745429028

##### Deliverables
- define `prettierrc`
- define `.prettierignore` for build folders

**Comment by TimDaub** [comment]
Added to "Paid tasks". My time estimate is: 1h

**Comment by lmpham1** [comment]
I'd like to work on this

**Comment by il3ven** [comment]
Closed via #45 and #50
