### ISSUE TITLE
allow dual use cjs and esm

### ISSUE THREAD

**Issue by TimDaub** [rugpullindex/svg-line-chart#8]
Currently, any build of svg-line-chart is targeting nodejs14 and commonjs: https://github.com/rugpullindex/svg-line-chart/blob/f205d99c088033e1b7d0a6732e4d948628f25d33/package.json#L8

However, there's an option that allows making modules available under `/esm` path. For a guide, see option 2: https://2ality.com/2019/10/hybrid-npm-packages.html

Deliverables:

- Preserve the option to import svg-line-chart as commonjs
- Add an option to import svg-line-chart under `/esm` as an ECMAScript module

**Comment by il3ven** [comment]
I'll like to work on this. Do I need to write a proposal first?

**Comment by TimDaub** [comment]
Hi @il3ven, to get paid, I suggest writing and getting a proposal approved first. How? See [here](https://github.com/rugpullindex/documents/blob/master/handbook.md#how-to-get-an-offer-approved-to-start-working-on-rpi). In case you just want to contribute as part of open source, that's fine too and doesn't require any prerequisite.
